package co.luism.diagnostics.common;

public enum ReturnCode {
	RET_OK(0), RET_NOK(1),
    RET_INVALID_MESSAGE_SIZE(2),
    RET_HELLO_VID_NOT_IN_CONFIGURATION(3),
	RET_HELLO_VID_ALREADY_ON_ANOTHER_CNX(4),
    RET_HELLO_VID_ALREADY_REGISTER(5), RET_VEHICLE_NOT_INITIALIZED(6),
    RET_HELLO_VEHICLE_NOT_SET(7), RET_SUSPEND_INVALID_TIMEOUT(8),
    RAT_SUSPEND_VEHICLE_NOT_FOUND(9), RET_DIAGD_RESPONSE_INVALID_FUNCTION(10),
    RET_HELLO_LS_TIMEOUT_NOT_SET(11), USER_PASS_CHANGE_VERIFY_NOT_MATCH(12),
    USER_PASS_CHANGE_CURRENT_PASS_NOT_MATCH(13), IMPORT_VEHICLE_ID_NOT_FOUND(14), 
    IMPORT_VEHICLE_ID_NOT_READ(15), IMPORT_IO_ERROR(16), IMPORT_VEHICLE_NOT_FOUND(17), 
    IMPORT_PROJECT_CODE_NOT_MATCH(18), IMPORT_ERROR_FILE_NOT_FOUND(19), IMPORT_VEHICLE_ID_NOT_MATCH(20);
	
	private final int value;

    private ReturnCode(int value) {
        this.value = value;
    }

    public int getValue() {
		return value;
	}
     


}
